### ISSUE TITLE
打洞一直失败

### ISSUE THREAD

**Issue by zhuwei** [zfunnily/hole-punching-go-libp2p#1]
没成功过。应该不是防火墙问题

**Comment by zfunnily** [comment]
> 没成功过。应该不是防火墙问题

我这是内网环境测试的， 如果relay-server在外网，可以把生成的地址中的ip替换成外网ip。

**Comment by zhuwei** [comment]
@zfunnily 这个我知道。server我在公网，我两个局域网打洞一直失败，两个朋友的网络，不是同一个局域网的两个客户端。
防火墙类型应该是支持打洞

**Comment by zfunnily** [comment]
> 

我拉go-libp2p库的源码来看了下， 直连的函数成这样了。

// DirectConnect is only exposed for testing purposes.
// TODO: find a solution for this.
func (s *Service) DirectConnect(p peer.ID) error {
	<-s.hasPublicAddrsChan
	return s.holePuncher.DirectConnect(p)
}

打洞应该是成功了。`<-s.hasPublicAddrsChan`这段代码拦截了。

我研究这个库主要是看它的测试用例和它的源码。打洞这块主要看 `holepuch/sv.go`文件。
协议名字是`holepuch.Protocol`
打洞函数是`s.host.SetStreamHandler(Protocol, s.handleNewStream)`。 

希望对你有所帮助。

**Comment by zhuwei** [comment]
@zfunnily 非常感谢

**Comment by kt5ttk99** [comment]
请问这个有解决方法了吗
